# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Seyoun Byun
first_name: Seyoun
middle_name: (Jess)
last_name: Byun
description: >-
  Ph.D. Candidate in Bioinformatics and Computational Biology at UNC-Chapel Hill
email: sbyun@unc.edu
lang: en
icon: ⚛️

url: "https://seyoun209.github.io"
baseurl: ""

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> • 
  Theme: <a href="https://github.com/alshedivat/al-folio">al-folio</a>

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_trophies:
  enabled: false

# -----------------------------------------------------------------------------
# Academic Info
# -----------------------------------------------------------------------------

cv: https://seyoun209.github.io/cv/
google_scholar: https://scholar.google.com/citations?hl=en&user=SEhfvSsAAAAJ
orcid: https://orcid.org/0000-0002-2915-6012

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Byun]
  first_name: [Seyoun, S.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  group_by: year
  group_order: descending
